export enum QueryKeys {
  CHECK_RUNS = "CHECK_RUNS",
  COMPARE = "COMPARE",
  PULL_REQUEST = "PULL_REQUEST",
  PULL_REQUEST_COMMENTS = "PULL_REQUEST_COMMENTS",
  PULL_REVIEWS = "PULL_REVIEWS",
  SEARCH_PULL_REQUESTS = "SEARCH_PULL_REQUESTS",
}
